import { StyleSheet } from "@react-pdf/renderer";

/**
 * Print palette — react-pdf can't read the HSL CSS vars, so the Secretariat
 * colours are pinned as hex here (light-mode print only; PDFs are never dark).
 */
export const PDF = {
  navy: "#12325B",
  navyDeep: "#0B2447",
  saffron: "#C15A15",
  green: "#1D6B3B",
  ink: "#14192A",
  body: "#3A3F4B",
  muted: "#5C6270",
  faint: "#8A8F9A",
  line: "#D9D6CC",
  lineFaint: "#ECEAE2",
  chip: "#F4F1E9",
  paper: "#FFFFFF",
} as const;

export const letterStyles = StyleSheet.create({
  page: {
    paddingTop: 48,
    paddingBottom: 56,
    paddingHorizontal: 56,
    fontFamily: "Times-Roman",
    fontSize: 11,
    color: PDF.ink,
    lineHeight: 1.5,
  },
  // Letterhead
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderBottomWidth: 2,
    borderBottomColor: PDF.navy,
    paddingBottom: 12,
    marginBottom: 4,
  },
  seal: {
    width: 34,
    height: 34,
    borderRadius: 17,
    borderWidth: 1.5,
    borderColor: PDF.saffron,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  sealText: { fontFamily: "Helvetica-Bold", fontSize: 13, color: PDF.navy },
  mpName: { fontFamily: "Helvetica-Bold", fontSize: 15, color: PDF.navy },
  mpRole: { fontFamily: "Helvetica", fontSize: 8.5, color: PDF.muted, marginTop: 2 },
  emblem: { fontFamily: "Helvetica", fontSize: 8, color: PDF.faint, textAlign: "right" },
  subBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderBottomWidth: 0.5,
    borderBottomColor: PDF.line,
    paddingVertical: 6,
    marginBottom: 22,
    fontFamily: "Helvetica",
    fontSize: 8.5,
    color: PDF.muted,
  },
  refBlock: { marginBottom: 18 },
  refRow: { flexDirection: "row", justifyContent: "space-between" },
  refLabel: { fontFamily: "Helvetica-Bold", fontSize: 9, color: PDF.ink },
  refValue: { fontFamily: "Courier", fontSize: 10, color: PDF.ink },
  recipient: { marginBottom: 16 },
  recipientName: { fontFamily: "Helvetica-Bold", fontSize: 10.5, color: PDF.ink },
  recipientLine: { fontSize: 10, color: PDF.body },
  subject: {
    fontFamily: "Helvetica-Bold",
    fontSize: 11,
    color: PDF.navy,
    marginBottom: 14,
    textDecoration: "underline",
  },
  para: { marginBottom: 11, textAlign: "justify" },
  signature: { marginTop: 26 },
  signName: { fontFamily: "Helvetica-Bold", fontSize: 12, color: PDF.ink },
  signRole: { fontSize: 9.5, color: PDF.muted },
  annexBox: {
    marginTop: 22,
    borderWidth: 0.5,
    borderColor: PDF.line,
    backgroundColor: PDF.chip,
    borderRadius: 4,
    padding: 10,
  },
  annexTitle: {
    fontFamily: "Helvetica-Bold",
    fontSize: 7.5,
    color: PDF.muted,
    letterSpacing: 0.6,
    marginBottom: 5,
  },
  annexItem: { fontFamily: "Helvetica", fontSize: 9, color: PDF.ink, marginBottom: 2 },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 56,
    right: 56,
    borderTopWidth: 0.5,
    borderTopColor: PDF.line,
    paddingTop: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    fontFamily: "Helvetica",
    fontSize: 7.5,
    color: PDF.faint,
  },
});

export const briefingStyles = StyleSheet.create({
  page: {
    paddingTop: 44,
    paddingBottom: 48,
    paddingHorizontal: 48,
    fontFamily: "Helvetica",
    fontSize: 10,
    color: PDF.ink,
    lineHeight: 1.4,
  },
  masthead: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    borderBottomWidth: 2,
    borderBottomColor: PDF.navy,
    paddingBottom: 10,
    marginBottom: 4,
  },
  brand: { fontFamily: "Helvetica-Bold", fontSize: 20, color: PDF.navy },
  brandSub: { fontFamily: "Helvetica", fontSize: 8.5, color: PDF.muted, marginTop: 3 },
  docType: { fontFamily: "Helvetica-Bold", fontSize: 10, color: PDF.saffron, textAlign: "right" },
  docMeta: { fontFamily: "Helvetica", fontSize: 8, color: PDF.muted, textAlign: "right", marginTop: 2 },
  subBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 6,
    marginBottom: 18,
    fontFamily: "Helvetica",
    fontSize: 8.5,
    color: PDF.muted,
    borderBottomWidth: 0.5,
    borderBottomColor: PDF.lineFaint,
  },
  sectionTitle: {
    fontFamily: "Helvetica-Bold",
    fontSize: 8.5,
    color: PDF.muted,
    letterSpacing: 0.8,
    marginBottom: 8,
  },
  kpiRow: { flexDirection: "row", gap: 8, marginBottom: 20 },
  kpiCard: {
    flex: 1,
    borderWidth: 0.5,
    borderColor: PDF.line,
    borderRadius: 4,
    padding: 9,
  },
  kpiLabel: { fontFamily: "Helvetica", fontSize: 7.5, color: PDF.muted, marginBottom: 3 },
  kpiValue: { fontFamily: "Helvetica-Bold", fontSize: 15, color: PDF.ink },
  kpiSub: { fontFamily: "Helvetica", fontSize: 7, color: PDF.faint, marginTop: 2 },
  item: {
    borderBottomWidth: 0.5,
    borderBottomColor: PDF.lineFaint,
    paddingVertical: 8,
    flexDirection: "row",
  },
  rank: { fontFamily: "Helvetica-Bold", fontSize: 11, color: PDF.faint, width: 22 },
  itemBody: { flex: 1 },
  itemHead: { flexDirection: "row", justifyContent: "space-between", marginBottom: 2 },
  itemTitle: { fontFamily: "Helvetica-Bold", fontSize: 10.5, color: PDF.ink, flex: 1 },
  urgencyTag: { fontFamily: "Helvetica-Bold", fontSize: 7.5, letterSpacing: 0.4 },
  itemMeta: { fontFamily: "Helvetica", fontSize: 8.5, color: PDF.muted, marginBottom: 3 },
  evidence: { fontFamily: "Helvetica", fontSize: 8.5, color: PDF.body, marginBottom: 2 },
  action: { fontFamily: "Helvetica-Bold", fontSize: 8.5, color: PDF.navy },
  footer: {
    position: "absolute",
    bottom: 22,
    left: 48,
    right: 48,
    borderTopWidth: 0.5,
    borderTopColor: PDF.line,
    paddingTop: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    fontFamily: "Helvetica",
    fontSize: 7.5,
    color: PDF.faint,
  },
});

export const URGENCY_HEX: Record<string, string> = {
  critical: "#A3311F",
  high: "#B77321",
  medium: "#8A7515",
  low: "#4A6A87",
};
